Added installation of shared libraries
ogdf/ogdf pull request #62
Opened 2020-10-05 09:15 UTC by emmenlau

This PR adds a minor change to the build instructions. It allows to install a shared build of OGDF into the `bin` directory. Without this PR, shared libraries are currently not installed.

Closes #57

2020-10-07 14:33 UTC, milsen requested changes
Thank you for your figuring this out and fixing it!
It would be nice if you could add my requested changes to your commit; other than that this looks good.

2020-10-07 14:33 UTC, milsen commented on cmake/coin.cmake
> +set(OGDF_INSTALL_BIN_DIR "bin" CACHE PATH "Installation path of OGDF library runtime")
```suggestion
set(COIN_INSTALL_BIN_DIR "bin" CACHE PATH "Installation path of COIN runtime targets")
```

2020-10-07 14:33 UTC, milsen commented on cmake/coin.cmake
>  mark_as_advanced(COIN_INSTALL_LIBRARY_DIR COIN_INSTALL_INCLUDE_DIR COIN_INSTALL_CMAKE_DIR)
```suggestion
mark_as_advanced(COIN_INSTALL_LIBRARY_DIR COIN_INSTALL_BIN_DIR COIN_INSTALL_INCLUDE_DIR COIN_INSTALL_CMAKE_DIR)
```

2020-10-07 14:33 UTC, milsen commented on cmake/coin.cmake
> +  RUNTIME DESTINATION "${OGDF_INSTALL_BIN_DIR}"
```suggestion
  RUNTIME DESTINATION "${COIN_INSTALL_BIN_DIR}"
```

2020-10-07 14:33 UTC, milsen commented on cmake/ogdf.cmake
> +set(OGDF_INSTALL_BIN_DIR "bin" CACHE PATH "Installation path of OGDF library runtime")
```suggestion
set(OGDF_INSTALL_BIN_DIR "bin" CACHE PATH "Installation path of OGDF runtime targets")
```

2020-10-07 14:33 UTC, milsen commented on cmake/ogdf.cmake
>  mark_as_advanced(OGDF_INSTALL_LIBRARY_DIR OGDF_INSTALL_INCLUDE_DIR OGDF_INSTALL_CMAKE_DIR)
```suggestion
mark_as_advanced(OGDF_INSTALL_LIBRARY_DIR OGDF_INSTALL_BIN_DIR OGDF_INSTALL_INCLUDE_DIR OGDF_INSTALL_CMAKE_DIR)
```

2020-10-13 09:17 UTC, emmenlau commented
Dear @milsen thanks for the thumbs up!

I've implemented your requested changes and squashed the commits (this is usually requested, but you did not explicitly say so, so I hope that was your expectation?).

Thanks for considering this PR, please review and/or merge!

2020-10-13 15:51 UTC, milsen commented
Thank you (also for squashing the commits). This PR looks good now, I'll merge it soon.

2020-10-15 12:05 UTC, milsen approved these changes

2020-10-15 12:07 UTC, merged